// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:906487213053:web:dad92fe75f82eb09a90794',
    messagingSenderId: '906487213053',
    projectId: 'mobileprog-dae19',
    authDomain: 'mobileprog-dae19.firebaseapp.com',
    storageBucket: 'mobileprog-dae19.firebasestorage.app',
    measurementId: 'G-V6EM0QE3BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:906487213053:android:a656b09265f8d3f6a90794',
    messagingSenderId: '906487213053',
    projectId: 'mobileprog-dae19',
    storageBucket: 'mobileprog-dae19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:906487213053:ios:79e5106fe605423ca90794',
    messagingSenderId: '906487213053',
    projectId: 'mobileprog-dae19',
    storageBucket: 'mobileprog-dae19.firebasestorage.app',
    iosBundleId: 'com.example.mobileprogrammingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:906487213053:ios:79e5106fe605423ca90794',
    messagingSenderId: '906487213053',
    projectId: 'mobileprog-dae19',
    storageBucket: 'mobileprog-dae19.firebasestorage.app',
    iosBundleId: 'com.example.mobileprogrammingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:906487213053:web:9821e1e149e45f1ca90794',
    messagingSenderId: '906487213053',
    projectId: 'mobileprog-dae19',
    authDomain: 'mobileprog-dae19.firebaseapp.com',
    storageBucket: 'mobileprog-dae19.firebasestorage.app',
    measurementId: 'G-60VW81N115',
  );
}